Document: python-seabreeze
Title: Debian python-seabreeze Manual
Author: <insert document author here>
Abstract: This manual describes what python-seabreeze is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-seabreeze/python-seabreeze.sgml.gz

Format: postscript
Files: /usr/share/doc/python-seabreeze/python-seabreeze.ps.gz

Format: text
Files: /usr/share/doc/python-seabreeze/python-seabreeze.text.gz

Format: HTML
Index: /usr/share/doc/python-seabreeze/html/index.html
Files: /usr/share/doc/python-seabreeze/html/*.html
